name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "hello-action-2020-04-15"
    
    - name: Docker push aliyun
      run: |
        docker login --username=1937583471@qq.com --password=${{ secrets.ALCHEMY_ALIYUN_PWD }} && \
        docker tag hello-action-2020-04-15 registry.cn-beijing.aliyuncs.com/alchemy_studio/demo:0.0.1 && \
        docker push registry.cn-beijing.aliyuncs.com/alchemy_studio/demo:0.0.1
      
      
    - name: Docker Push
      uses: opspresso/action-docker@v0.2.8
      with:
          args: --docker
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.ALCHEMY_PACKAGES }}
        REGISTRY: "docker.pkg.github.com"
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "hello-action-2020-04-15"
        TAG_NAME: "v0.0.1"
        LATEST: "true"

