name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker Push
      uses: opspresso/action-docker@v0.2.8
      with:
          args: --docker
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: my-image-name:$(date +%s)
        TAG_NAME: "v0.0.1"
        LATEST: "true"

